Web/MyRecipes.Web/Areas/Administration/Controllers/AdministrationController.cs
namespace MyRecipes.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Common;
    using MyRecipes.Web.Controllers;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class AdministrationController : BaseController
    {
    }
}

Web/MyRecipes.Web/Areas/Administration/Controllers/DashboardController.cs
namespace MyRecipes.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels.Administration.Dashboard;

    public class DashboardController : AdministrationController
    {
        private readonly ISettingsService settingsService;

        public DashboardController(ISettingsService settingsService)
        {
            this.settingsService = settingsService;
        }

        public IActionResult Index()
        {
            var viewModel = new IndexViewModel { SettingsCount = this.settingsService.GetCount(), };
            return this.View(viewModel);
        }
    }
}

Web/MyRecipes.Web/Controllers/BaseController.cs
namespace MyRecipes.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class BaseController : Controller
    {
    }
}

Web/MyRecipes.Web/Controllers/GatherRecipesController.cs
namespace MyRecipes.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Services;

    public class GatherRecipesController : BaseController
    {
        private readonly IGotvachBgScraperService gotvachBgScraperService;

        public GatherRecipesController(IGotvachBgScraperService gotvachBgScraperService)
        {
            this.gotvachBgScraperService = gotvachBgScraperService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        public async Task<IActionResult> Add()
        {
            await this.gotvachBgScraperService.ImportRecipesAsync();

            return this.RedirectToAction("Index");
        }
    }
}

Web/MyRecipes.Web/Controllers/HomeController.cs
namespace MyRecipes.Web.Controllers
{
    using System.Diagnostics;

    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels;
    using MyRecipes.Web.ViewModels.Home;

    public class HomeController : BaseController
    {
        private readonly IGetCountsService getCountsService;

        public HomeController(IGetCountsService getCountsService)
        {
            this.getCountsService = getCountsService;
        }

        public IActionResult Index()
        {
            var counts = this.getCountsService.GetCounts();
            var viewModel = new IndexViewModel
            {
                CategoriesCount = counts.CategoriesCount,
                RecipesCount = counts.RecipesCount,
                IngredientsCount = counts.IngredientsCount,
                ImagesCount = counts.ImagesCount,
            };

            return this.View(viewModel);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/MyRecipes.Web/Controllers/RecipesController.cs
namespace MyRecipes.Web.Controllers
{
    using System;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels.Recipes;

    public class RecipesController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly IRecipeService recipeService;
        private readonly IWebHostEnvironment environment;

        public RecipesController(
            ICategoriesService categoriesService,
            IRecipeService recipeService,
            IWebHostEnvironment environment)
        {
            this.categoriesService = categoriesService;
            this.recipeService = recipeService;
            this.environment = environment;
        }

        [Authorize]
        public IActionResult Create()
        {
            var viewModel = new CreateRecipeInputModel();
            viewModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateRecipeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            try
            {
                await this.recipeService.CreateAsync(input, userId, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }

            return this.Redirect("/");
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;
            var viewModel = new RecipesListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                RecipesCount = this.recipeService.GetCount(),
                Recipes = this.recipeService.GetAll<RecipeInListViewModel>(id, ItemsPerPage),
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var recipe = this.recipeService.GetById<SingleRecipeViewModel>(id);

            return this.View(recipe);
        }
    }
}

Web/MyRecipes.Web/Controllers/SettingsController.cs
namespace MyRecipes.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Data.Common.Repositories;
    using MyRecipes.Data.Models;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels.Settings;

    public class SettingsController : BaseController
    {
        private readonly ISettingsService settingsService;

        private readonly IDeletableEntityRepository<Setting> repository;

        public SettingsController(ISettingsService settingsService, IDeletableEntityRepository<Setting> repository)
        {
            this.settingsService = settingsService;
            this.repository = repository;
        }

        public IActionResult Index()
        {
            var settings = this.settingsService.GetAll<SettingViewModel>();
            var model = new SettingsListViewModel { Settings = settings };
            return this.View(model);
        }

        public async Task<IActionResult> InsertSetting()
        {
            var random = new Random();
            var setting = new Setting { Name = $"Name_{random.Next()}", Value = $"Value_{random.Next()}" };

            await this.repository.AddAsync(setting);
            await this.repository.SaveChangesAsync();

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Web/MyRecipes.Web/Controllers/VotesController.cs
namespace MyRecipes.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels.Votes;

    [ApiController]
    [Route("api/[controller]")]
    public class VotesController : BaseController
    {
        private readonly IVoteService votesService;

        public VotesController(IVoteService votesService)
        {
            this.votesService = votesService;
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult<PostVoteResponseModel>> Post(PostVoteInputModel input)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            await this.votesService.SetVoteAsync(input.RecipeId, userId, input.Value);
            var averageVote = this.votesService.GetAverageVotes(input.RecipeId);
            return new PostVoteResponseModel { AverageVote = averageVote };
        }
    }
}

Web/MyRecipes.Web/Areas/Administration/Views/Dashboard/Index.cshtml
@model MyRecipes.Web.ViewModels.Administration.Dashboard.IndexViewModel
@{
    this.ViewData["Title"] = "Admin dashboard";
}

<h1>@this.ViewData["Title"]</h1>
Settings: @this.Model.SettingsCount

Web/MyRecipes.Web/Views/Home/Index.cshtml
@using MyRecipes.Common
@model MyRecipes.Web.ViewModels.Home.IndexViewModel
@{
    this.ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to @GlobalConstants.SystemName!</h1>
    <div class="col-md-4 offset-md-4">
        <p>We have:</p>
        <ul class="list-group">
            <li class="list-group-item bg-info">Recipes: @Model.RecipesCount</li>
            <li class="list-group-item bg-light">Categories: @Model.CategoriesCount</li>
            <li class="list-group-item bg-info">Ingredients: @Model.IngredientsCount</li>
            <li class="list-group-item bg-light">Images: @Model.ImagesCount</li>
        </ul>
    </div>
</div>

Web/MyRecipes.Web/Views/Recipes/All.cshtml
@model MyRecipes.Web.ViewModels.Recipes.RecipesListViewModel
@{
    this.ViewData["Title"] = "All Recipes, Page " + Model.PageNumber;
}
<h1>@this.ViewData["Title"]</h1>
<hr />
<div class="row">
    @foreach (var recipe in Model.Recipes)
    {
        <div class="media col-md-4">
            <img src="@recipe.ImageUrl" width="100" class="mr-3 img-responsive">
            <div class="media-body">
                <h5 class="mt-0"><a asp-action="ById" asp-route-id="@recipe.Id">@recipe.Name</a></h5>
                @recipe.CategoryName
            </div>
        </div>
    }
</div>
<hr />
<partial name="_PagingPartial" model="@Model" />

Web/MyRecipes.Web/Views/Recipes/ById.cshtml
@model MyRecipes.Web.ViewModels.Recipes.SingleRecipeViewModel
@{
    this.ViewData["Title"] = Model.Name;
}
<div class="single-recipe-layout1">
    <div class="ctg-name">@Model.CategoryName</div>
    <h2 class="item-title">@this.ViewData["Title"]</h2>
    <div class="row mb-4">
        <div class="col-xl-9 col-12">
            <ul class="entry-meta">
                <li class="single-meta">
                    <i class="far fa-calendar-alt"></i>
                    @Model.CreatedOn.ToShortDateString()
                </li>
                <li class="single-meta">
                    <i class="fas fa-user"></i> by
                    @if (string.IsNullOrWhiteSpace(Model.AddedByUserUserName))
                    {
                        <a href="@Model.OriginalUrl" target="_blank"> recepti.gotvach.bg</a>
                    }
                    else
                    {
                        <span>@Model.AddedByUserUserName</span>
                    }
                </li>
                <li class="single-meta">
                    <ul class="item-rating">
                        <li class="star-fill" data-vote="1"><i class="fas fa-star"></i></li>
                        <li class="star-fill" data-vote="2"><i class="fas fa-star"></i></li>
                        <li class="star-fill" data-vote="3"><i class="fas fa-star"></i></li>
                        <li class="star-fill" data-vote="4"><i class="fas fa-star"></i></li>
                        <li class="star-fill" data-vote="5"><i class="fas fa-star"></i></li>
                        <li><span id="averageVoteValue">@Model.AverageVote.ToString("0.0")</span><span> / 5</span> </li>
                    </ul>
                </li>
            </ul>
        </div>

    </div>
    <div class="item-figure">
        <img class="img-fluid w-50" src="@Model.ImageUrl" alt="@Model.Name">
    </div>
    <div class="item-feature">
        <ul>
            <li>
                <div class="feature-wrap">
                    <div class="media">
                        <div class="feature-icon">
                            <i class="far fa-clock"></i>
                        </div>
                        <div class="media-body space-sm">
                            <div class="feature-title">PREP TIME</div>
                            <div class="feature-sub-title">@Model.PreparationTime.TotalMinutes Mins</div>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="feature-wrap">
                    <div class="media">
                        <div class="feature-icon">
                            <i class="fas fa-utensils"></i>
                        </div>
                        <div class="media-body space-sm">
                            <div class="feature-title">COOK TIME</div>
                            <div class="feature-sub-title">@Model.CookingTime.TotalMinutes Mins</div>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="feature-wrap">
                    <div class="media">
                        <div class="feature-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        <div class="media-body space-sm">
                            <div class="feature-title">SERVING</div>
                            <div class="feature-sub-title">
                                @Model.PortionsCount
                                @if (Model.PortionsCount > 1)
                                {
                                    <span>People</span>
                                }
                                else
                                {
                                    <span>Person</span>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="feature-wrap">
                    <div class="media">
                        <div class="feature-icon">
                            <i class="fa fa-list-ol"></i>
                        </div>
                        <div class="media-body space-sm">
                            <div class="feature-title">CATEGORY RECIPES</div>
                            <div class="feature-sub-title">@Model.CategoryRecipesCount</div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="making-elements-wrap">
        <div class="row">
            <div class="col-md-6">
                <p class="item-description">
                    @Model.Instructions
                </p>
            </div>
            <div class="col-md-6">
                <div class="ingridients-wrap">
                    <h3 class="item-title"><i class="fas fa-list-ul"></i>Ingridients</h3>
                    @foreach (var ingredient in Model.Ingredients)
                    {
                        <div class="checkbox checkbox-primary">
                            <label for="checkbox1">@ingredient.Quantity @ingredient.IngredientName</label>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<form method="post" id="antiForgeryForm"></form>
    @section Scripts{
        <script>
            $("li[data-vote]").each(function (el) {
                $(this)[0].click(function () {
                    var value = $(this).attr("data-vote");
                    var recipeId = @Model.Id;
                    var antiForgeryToken = $('#antiForgeryForm input[name=_RequestVerificationToken]').val();
                    var data = { recipeId: recipeId, value: value };

                    $.ajax({
                        type: "POST",
                        url: "/api/Votes",
                        data: JSON.stringify(data),
                        headers: {
                            'X-CSRF-TOKEN': antiForgeryToken
                        },
                        success: function (data) {
                            $('#averageVoteValue').html(data.averageVote.toFixed(1));
                        },
                        contentType: 'application/json',

                    })
                 })
            });
        </script>
    }

Web/MyRecipes.Web/Views/Recipes/Create.cshtml
@model MyRecipes.Web.ViewModels.Recipes.CreateRecipeInputModel
@{
    this.ViewData["Title"] = "Add new recipe";
    var categoryItem = this.Model.CategoriesItems.Select(x => new SelectListItem(x.Value, x.Key));
}


<form method="post" class="col-md-6 offset-md-3" enctype="multipart/form-data">
    <h1>@this.ViewData["Title"]</h1>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Instructions"></label>
        <textarea asp-for="Instructions" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Instructions" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PreparationTime"></label>
        <input asp-for="PreparationTime" class="form-control" />
        <span asp-validation-for="PreparationTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CookingTime"></label>
        <input asp-for="CookingTime" class="form-control" />
        <span asp-validation-for="CookingTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PortionsCount"></label>
        <input asp-for="PortionsCount" class="form-control" />
        <span asp-validation-for="PortionsCount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId"></label>
        <select asp-for="CategoryId" class="form-control" asp-items="categoryItem"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Images"></label>
        <input asp-for="Images" class="form-control" />
        <span asp-validation-for="Images" class="text-danger"></span>
    </div>
    <div id="IngredientsContainer">
        <label asp-for="Ingredients"></label>
        <a class="btn btn-success" onclick="AddMoreIngredients()">+</a>
    </div>
    <input type="submit" class="btn btn-primary" />
</form>

@section Scripts{
    <script>
        var ingredientIndex = 0;
        function AddMoreIngredients() {
            $("#IngredientsContainer")
                .append("<div class='form-control'>Name: <input type = 'text' name='Ingredients[" + ingredientIndex + "].IngredientName' /> Qantity: <input type = 'text' name='Ingredients[" + ingredientIndex + "].Quantity' /></div>");
            ingredientIndex++;
        }
    </script>
}

Web/MyRecipes.Web/Views/Settings/Index.cshtml
@model MyRecipes.Web.ViewModels.Settings.SettingsListViewModel

@{
    this.ViewData["Title"] = "Settings";
}

<h1>@this.ViewData["Title"]</h1>

@foreach (var setting in this.Model.Settings)
{
    <div>@setting.Id: @setting.NameAndValue</div>
}

<a asp-action="InsertSetting" class="btn btn-primary">Insert new</a>

Web/MyRecipes.Web/Views/Shared/_Layout.cshtml
@using MyRecipes.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />    
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <div id="wrapper" class="wrapper">
        <header>
            <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="All">All Recipe</a>
                            </li>
                            @if (this.User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="Create">Create Recipe</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @this.RenderBody()
            </main>
        </div>
        <footer class="ranna-bg-dark">
            <div class="container">
                &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/MyRecipes.Web/Views/Shared/_PagingPartial.cshtml
@model MyRecipes.Web.ViewModels.Recipes.PagingViewModel

<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text>} ">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 3; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 3; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text>}">
            <a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>